nome = str(input("Digite o nome: "))
cpf = str(input("Digite o número do CPF: "))
rg = str(input("Digite o número do RG: "))
nasc = str(input("Digite a data de nascimento: "))
sexo = str(input("Digite o sexo: "))
peso = float(input("Digite o peso: "))
tipo_sanguineo = str(input("Digite o tipo sanguíneo: "))
renda = float(input("Qual o valor da renda: "))
end = str(input("Digite o endereço: "))
tel = int(input("Digite o número do Telefone: "))
cidade = str(input("Cidade e estado: "))

print(f"Nome________________________ {nome}")
print(f"CPF________________________ {cpf}")
print(f"RG________________________ {rg}")
print(f"Data de nascimento________________________ {nasc}")
print(f"Sexo________________________ {sexo}")
print(f"Peso________________________ {peso} KG")
print(f"Tipo Sanguíneo________________________ {tipo_sanguineo}")
print(f"Renda________________________ {renda}")
print(f"Endereço________________________ {end}")
print(f"Tel________________________ {tel}")
print(f"Cidade e Estado________________________ {cidade}")

