a = "JOAO VITOR "
print(a.casefold())

#casefold É USADO PARA TRANSFORMAR AS LETRAS MAIÚSCULAS EM MINÚSCULAS

b = "JOAO VITOR"
print(a.lower())

#lower TEM A MESMA FUNÇÃO DA CASEFOLD TRANSFORMAR AS LETRAS MAIÚSCULAS EM MINÚSCULAS